openapi: 3.0.0
info:
  title: EasyMovies API
  version: "1.0"
  description: "API per applicazione EasyMovies"
paths:
  /users/register:
    post:
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              allOf:
                - $ref: '#/components/schemas/UserCredentials'
                - $ref: '#/components/schemas/UserData'
                - $ref: '#/components/requestBodies/Image'
          image/jpeg:
            schema:
              type: string
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Register new User
      operationId: Register new User
  /users/login:
    post:
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Access with Credentials
      operationId: Access with Credentials
  /users/{username}/logout:
    parameters:
      - name: username
        in: path
        required: true
        description: User that logs out
        schema:
          type : string
    post:
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal Server Error
      summary: Log out and delete session
      operationId: Log out and delete session
  /users/{username}:
    parameters:
      - name: username
        in: path
        required: true
        description: User to which belongs the information
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserData'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get Public User Data
      operationId: Get Public User Data
    delete:
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a User
      operationId: Delete a User
  /users/{username}/profilepic:
    parameters:
      - name: username
        in: path
        required: true
        description: User to which belongs the profilepic
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            image/jpeg:
              schema:
                type: string
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User Profile Picture
      operationId: Get User Profile Picture
  /users/{username}/reviews:
    parameters:
      - name: username
        in: path
        required: true
        description: User to which the reviews refer to
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User Reviews
      operationId: Get User Reviews
  /users/{username}/playlists:
    parameters:
      - name: username
        in: path
        required: true
        description: User to which the playlists belong to
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Playlist'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get User Playlists
      operationId: Get User Playlists
    post:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create a new Playlist
      operationId: Create a new Playlist
    delete:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
                - playlistId
              properties:
                playlistId:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete Playlist
      operationId: Delete Playlist
  /users/{username}/playlists/{playlistId}:
    parameters:
      - name: username
        in: path
        required: true
        description: User to which the playlist belongs
        schema:
          type : string
      - name: playlistId
        in: path
        required: true
        description: The playlist id
        schema:
          type : string
    post:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
                - movieId
              properties:
                movieId:
                  type: string
      responses:
        "201":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Add movie to playlist
      operationId: Add movie to playlist
    patch:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
                - newname
              properties:
                newname:
                  type: string
      responses:
        "201":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Edit playlist name
      operationId: Edit playlist name
    delete:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
                - movieId
              properties:
                movieId:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Remove movie from playlist
      operationId: Remove movie from playlist
  /movies/{movieId}:
    parameters:
      - name: movieId
        in: path
        required: true
        description: The id of the movie
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/Movie'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get Movie Data
      operationId: Get Movie Data
  /movies/{movieId}/reviews:
    parameters:
      - name: movieId
        in: path
        required: true
        description: The id of the movie
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get Movie Reviews
      operationId: Get Movie Reviews
    post:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        "201":
          description: Review Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Add Movie Review
      operationId: Add Movie Review
    delete:
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              required:
                - movieId
                - username
              properties:
                movieId:
                  type: string
                username:
                  type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete Movie Review
      operationId: Delete Movie Review
    patch:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Modify Movie Review
      operationId: Modify Movie Review
  /catalog/{catalogName}:
    parameters:
      - name: catalogName
        in: path
        required: true
        description: The naem of the catalog
        schema:
          type : string
    get:
      responses:
        "200":
          description: OK
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get Catalog Movies List
      operationId: Get Catalog Movies List
servers:
  - url: https://localhost:5000/api/v1/
components:
  schemas:
    UserCredentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    UserData:
      type: object
      required:
      - name
      - surname
      - username
      properties:
        name:
          type: string
        surname:
          type: string
        username:
          type: string
    Movie:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        overview:
          type: string
        trailerUrl:
          type: string
        duration:
          type: string
        releaseDate:
          type: string
        genre:
          type: string
    Review:
      type: object
      required:
      - movieId
      - username
      - title
      - content
      - rate
      properties:
        movieId:
          type: string
        username:
          type: string
        title:
          type: string
        content:
          type: string
        rate:
          type: number
          format: float
    Playlist:
      type: object
      properties:
        uername:
          type: string
        name:
          type: string
        movies:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
  requestBodies:
    Image:
      description: An image.
      content:
        image/jpg:
          schema:
            type: string
