FORMAT: 1A
HOST: https://localhost:5000/

# EasyMovies API
## User Registration [/users/register]

### Register new User [POST]

+ Request (application/json)

        {
            username: 'johnsmith',
            password: 'password123',
            name: 'John',
            surname: 'Smith'
        }
        
+ Response 200 (application/json)
        
        {
            sessionId: 'fdsk-jhbl-aflb-hdsj',
        }
        
+ Response 409
    
        {
            error: 'User already exists',
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## User Login [/users/login]

### Access with Credentials [POST]

+ Request (application/json)

        {
            username: 'johnsmith',
            password: 'password123',
        }
        
+ Response 200 (application/json)
        
        {
            sessionId: 'fdsk-jhbl-aflb-hdsj',
        }
        
+ Response 401
    
        {
            error: 'Wrong Credentials',
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## Public User Data [/users/{username}]

### Get Public User Data [GET]
        
+ Response 200 (application/json)
         
        {
            name: 'John',
            surname: 'Smith',
            reviews: [
                {},{}...
            ]
        }
        
+ Response 404
    
        {
            error: 'User not found',
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## User Playlists [/users/{username}/playlists]

### Get User Playlists [GET]
        
+ Response 200 (application/json)
        
        {
            playlists: [
                {},{}...
            ]
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

### Create a new Playlist [POST]
        
+ Response 200 (application/json)
        
        {
            playlistName: 'watch later',
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## User Playlist Data [/users/{username}/playlists/{playlistId}]

### Get Playlist Data [GET]
        
+ Response 200 (application/json)
        
        {
            movies: [{movie}, {movie}],
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

### Delete Playlist [DELETE]
        
+ Response 200 (application/json)
        
        {
            
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## Movie Data [/movies/{movieId}]

### Get Movie Data [GET]
        
+ Response 200 (application/json)
        
        {
            data varia
            reviews:[{},{}, {}];//ne ritorno esattamente 3
        }
        
+ Response 404
        
        {
            error: 'Movie not found',
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## Movie Reviews [/movies/{movieId}/reviews]

### Get Movie Reviews [GET]
        
+ Response 200 (application/json)
        
        {
            reviews:[{},{}, {}, ...]
        }
        
+ Response 404
        
        {
            error: 'Movie not found',
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }
        

## Movies Catalog [/catalog/{catalogName}]

### Get Catalog Movies List [GET]
        
+ Response 200 (application/json)
        
        {
            [{movie}, {movie}, ...]
        }
        
+ Response 500
        
        {
            error: 'Internal Server error',
        }